name: Build DeepslateMC
on: [ push, pull_request ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.1.0
    - name: Set up JDK 17
      uses: actions/setup-java@v3.6.0
      with:
        java-version: 17.0.5
        distribution: 'temurin'
    - name: Configure Git
      run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "Github Actions"
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Apply patches
      run: ./gradlew applyPatches
    - name: Generate Paperclip Jar
      run: ./gradlew createReobfPaperclipJar
    - name: Upload Paperclip
      uses: actions/upload-artifact@v3.1.1
      with:
        name: DeepslateMC
        path: build/libs/deepslateMC-paperclip-1.19.2-R0.1-SNAPSHOT-reobf.jar
